### PR TITLE
ex2,3 wb band size

### LINKED ISSUE #169: NSF Exercise 3 - western blot bands are incorrect
I haven't gone through all of the bands in detail, but bands are appearing where there shouldn't be any bands. For example, the WT EGFR sample with the FLAG or His antibodies should be blank. @annagav, would you like to go through the coding Excel spreadsheet together?

### PR DESCRIPTION
**Pull request by annagav**
Fix #169 and #161

### CODE REVIEW

**Comment by giocalitri** [comment]
cannot see any change in the "Files changed" tab...

**Comment by annagav** [comment]
Diff is still very big. Please look at the changes locally:
`git diff HEAD^ HEAD`

**Comment by pdpinch** [comment]
Functionally, this looks good except for one question. 

In #161 @laleman wrote:

> 6xHis antibody should detect at 84 kDa (high intensity) in 'his-prox-flag growth media', 40 kDa (med intensity) in 'his-prox-flag growth media+prok', and 232 kDA high intensity in 'his-proy-flag growth media'.

However, I got the following result:

screen shot 2015-07-20 at 10 34 49 pm

This looks to me like 'his-prox-flag growth media' and 'his-prox-flag growth media+prok' got the same bands. Is that correct?

**Comment by ald32** [comment]
Yes, that's correct. It looks like both samples 7 and 8 are giving the same bands where sample 7 should have a band at 84 kDa (high intensity) and sample 8 should have a band at 40 kDa (medium intensity). In addition, sample 9 should have a band at 232 kDa. I'm not sure if sample 10 should have a band at 232 kDa though.

**Comment by pdpinch** [comment]
@annagav I just want to make sure I understand the code changes that I'm seeing. 

It looks like you've replaced the `intensity` strings (`'none','med','high'`) with integer values. Is that right? Are those defined anywhere?

Also, there are comments sprinkled throughout when you set the `intensity`. Are those describing the meaning of the integer, or are those old values? If it's the latter, you should just remove the comments. I can live with the former.

**Comment by annagav** [comment]
The values of the intensity are not defined anywhere. In the coding for the exercise we have an estimate of how thick the bands should appear relative to each other. 

The comments I left indicate other values of size and intensity for the same sample. Sometimes a sample  can have two three bands.

**Comment by ald32** [comment]
Sample 10 shouldn't have any bands (just like Samples 1-6).

**Comment by pdpinch** [comment]
Thanks Anna. This is looking good to me know and appears to address #161 completely. I'll merge. 

screen shot 2015-07-22 at 2 33 58 pm

**Pull request merged**
