### PR TITLE
sutd2: added more images to slide_parser

### PR DESCRIPTION
**Pull request by annagav**

### CODE REVIEW

**Comment by pdpinch** [comment]
What's this for?

It seems like there should be way to do this that involves less typing.

**Comment by laleman** [comment]
I do not know what this is referring to.

**Comment by pdpinch** [comment]
Sorry, that was a question for @annagav 

> What's this for?
> It seems like there should be way to do this that involves less typing.

**Comment by annagav** [comment]
This slide_parser tells the microscopy parser to assign these images to a specific treatment.

**Pull request merged**
