### PR TITLE
ab: intensity page format

### LINKED ISSUE #452: Band intensity page: formatting and edits for the table
The table should be formatted like other tables where the headings are in bold, etc. so that it is clear that they are headings. 

It is hard to see the numbers next to each sample. Can you indent the text slightly (in both the first and second rows) so that it is easy to see each sample number (and tell that the sample name goes onto two lines)? 

The lysate type, size (kDa), and relative band intensity appear to be vertically bottom aligned within each row. Can you vertically center these items in each row?

In the heading for the Size column, please add a space between 'Size' and '(kDa)'. It should read: 'Size (kDa)'

### PR DESCRIPTION
**Pull request by annagav**
Fix #452, #445

### CODE REVIEW

**Comment by noisecapella** [comment]
Is this part done? I'm not sure what to look for exactly. Everything else looks good to me

> It is hard to see the numbers next to each sample. Can you indent the text slightly (in both the first and second rows) so that it is easy to see each sample number (and tell that the sample name goes onto two lines)?
> 
> The lysate type, size (kDa), and relative band intensity appear to be vertically bottom aligned within each row. Can you vertically center these items in each row?

**Comment by annagav** [comment]
The numbers are separate from the text. So I think that is done. 
As for the vertical alignment, I think having it aligned with the first row makes more clear. It didn't look good when aligned in the center, since the second row is not full and some rows don't have second line.

**Comment by noisecapella** [comment]
Sounds good to me :+1:

**Comment by noisecapella** [comment]
FYI I think you need to put the Fix statements on separate lines. It doesn't look like #445 was closed by this merge

**Pull request merged**
