### PR TITLE
Switched tests to use latest stable chromium

### PR DESCRIPTION
**Pull request by noisecapella**
#### What's this PR do?

Switched from Firefox to Chromium. This was part of the work to fix the build which ended up not being necessary but it's still a good idea since this is the only browser supported

### CODE REVIEW

**Comment by annagav** [comment]
@noisecapella, Could you please take a look at the 'Developers Guide' on selenium testing to see if it needs to be updated with these new changes?

**Comment by pdpinch** [comment]
I can take a look. I already noticed a few cosmetic errors in these instructions.

**Comment by noisecapella** [comment]
Sure, from a quick glance it looks we need to update:
- the port changed from 4444 to 9515 (not sure what `14444` was for)
- Instead of the seleniumdriver jar it now uses the chromedriver binary.

**Comment by annagav** [comment]
👍

**Comment by noisecapella** [comment]
I'll merge this then create an issue to update the developer's guide

**Pull request merged**
