### PR TITLE
creating AUTHORS file with names from TLO documentation

### PR DESCRIPTION
**Pull request by pdpinch**

### CODE REVIEW

**Comment by pdpinch** [comment]
@ald32 is this a complete list? 

+Alison Brauneis ald32@mit.edu
+Lourdes M Aleman laleman@mit.edu
+Ivica Ceraj iceraj@gmail.com
+Anna Gavrilman anna.gavrilman@gmail.com
+Peter Pinch pdpinch@mit.edu
+Brandon DeRosier bdero@mit.edu
+Carson Gee cgee@mit.edu
+Shloka R Kini skini@mit.edu
+Lisa Weingarten weingarten.lisa@gmail.com

(you can comment at https://github.com/starteam/starcellbio_html/pull/422/files)

**Comment by ald32** [comment]
Yes that is the complete authors list. Although Carson gave me: x@carsongee.com as his email address.

Thank you!

**Comment by pdpinch** [comment]
Good catch. That's fixed now.

**Comment by ald32** [comment]
I hate to add to this list, but Lourdes reminded me that our graphic designer made images and icons that we use in StarCellBio and now I think that we need to add Jamie Waters to our list. How hard is it to add another author?

**Pull request merged**
