### PR TITLE
ab: remove dashboard login message

### PR DESCRIPTION
**Pull request by annagav**

### CODE REVIEW

**Comment by pdpinch** [comment]
Do we not use this block for error messages?

**Comment by pdpinch** [comment]
Or maybe I misunderstood where this message is displayed.

**Comment by annagav** [comment]
It was displayed above the dashboard. You can still see it in the dev server.

**Comment by noisecapella** [comment]
The linked issue says that the message should be changed, not removed. Is the intent of the issue now to remove the message? If so feel free to merge :+1:

**Pull request merged**
