### PR TITLE
Release v0.7.0

### LINKED ISSUE #141: New SCB release for Django 1.7 upgrade and migrations
Do we want to make this one a feature release (v0.7.0)?

### PR DESCRIPTION
**Pull request by bdero**
Closes #141 

DO NOT MERGE UNTIL:
- Dev/prod environment is compatible
- #44 is resolved

Change summary:
- Upgrade to Django 1.7
- Add initial migration
- Remove many unnecessary things: master_model.js.backup, coin-slider, ui_old
- Lots of work on FACS

### CODE REVIEW

**Comment by pdpinch** [comment]
@bdero is this waiting for review?

**Comment by bdero** [comment]
Yes, how do you feel about the version bump to 0.7.0?

**Comment by carsongee** [comment]
Wasn't there still some experiment stuff to do for FACS?  Also, we can't actually do a production release of this due to the python 2.6 issue not being resolved

**Comment by pdpinch** [comment]
Oh, it's a production release? We aren't ready for that yet. 

We still need feedback on the last scbdev release, and @annagav is still working on NSF #1

**Comment by bdero** [comment]
Yes, I should have mentioned that this shouldn't be merged just yet. I'll add those to the description. Maybe I should close this until we're ready?

**Pull request closed without merging**
