### PR TITLE
Fix image names to match production deployment

### PR DESCRIPTION
**Pull request by bdero**

### CODE REVIEW

**Comment by carsongee** [comment]
What is a deplotment?  Sounds awesome

**Comment by bdero** [comment]
:hamburger:

**Comment by carsongee** [comment]
delicious deplotment. I see the couple of the lower cased versions˘ referenced:

```
html_app/ug2/user_guide.html:              "../media/uploads/starcellbio/scb_western_develop.png"
html_app/ug2/user_guide.html:              "../media/uploads/starcellbio/scb_western_sample_prep.png"
```

although I think those URL roots are wrong, and no idea what the context is, but you might want to follow consistency there.

**Comment by bdero** [comment]
Those references are to images being hosted outside of the app. No worries, though, they all seem to get mysteriously overridden on the client side with selectors like this:

```
$('img[src="../media/uploads/starcellbio/scb_western_sample_prep.png"]').attr('src', '../../../images/user_guide/SCB_Western_Sample_prep.png');
```

I'll be getting deeper into it as I start clearing out some more of the generated files scattered about. More PRs for that momentarily.

**Pull request merged**
