### PR TITLE
Add mail server to development system

### PR DESCRIPTION
**Pull request by carsongee**
This adds a mail server to the vagrant system.  After this merges, you should be able run `vagrant provision`, and creating accounts should work without an error

### CODE REVIEW

**Comment by annagav** [comment]
I have created an account and logged in successfully, but have not received an email confirmation.

**Comment by pdpinch** [comment]
The e-mail confirmation worked for me on scbdev.odl.mit.edu 

Where were you trying it @annagav ?

**Comment by annagav** [comment]
I was testing it locally.

**Comment by carsongee** [comment]
You might try restarting your vagrant box and signing up again.  If that doesn't work, you may want to look at `cat /var/log/syslog | grep postfix` to see if there are any obvious issues.  All that said, being able to actually send mail from your vagrant box is going to depend on a lot of different factors (like what IP you have and where you are sending the e-mail too), so it may just not ever get off your vagrant box.  However, it will be in the postfix message queue and you can read it from there.

**Comment by bdero** [comment]
I quickly tried this PR in a fresh vagrant environment and it's not completely working out of the box for me, but it's working enough.

The email didn't send, but the message showed up in the queue

``` bash
(starcellbio)vagrant@vagrant-ubuntu-trusty-64:/vagrant$ mailq
-Queue ID- --Size-- ----Arrival Time---- -Sender/Recipient-------
6D3B160207      601 Tue Apr 14 16:17:16  starcellbio-admin@mit.edu
(host DMZ-MAILSEC-SCANNER-6.mit.edu[18.7.68.35] refused to talk to me: 554 5.7.1 Delivery not authorized)
                                         bdero@mit.edu

-- 1 Kbytes in 1 Request.
```

Of course, the syslog indicates the same issue:

```
Apr 14 16:22:46 vagrant-ubuntu-trusty-64 postfix/smtp[25261]: 6D3B160207: host DMZ-MAILSEC-SCANNER-6.mit.edu[18.7.68.35] refused to talk to me: 554 5.7.1 Delivery not authorized
Apr 14 16:22:46 vagrant-ubuntu-trusty-64 postfix/smtp[25261]: 6D3B160207: host DMZ-MAILSEC-SCANNER-2.mit.edu[18.9.25.13] refused to talk to me: 554 5.7.1 Delivery not authorized
Apr 14 16:22:46 vagrant-ubuntu-trusty-64 postfix/smtp[25261]: 6D3B160207: host DMZ-MAILSEC-SCANNER-7.mit.edu[18.7.68.36] refused to talk to me: 554 5.7.1 Delivery not authorized
Apr 14 16:22:46 vagrant-ubuntu-trusty-64 postfix/smtp[25261]: 6D3B160207: host DMZ-MAILSEC-SCANNER-8.mit.edu[18.7.68.37] refused to talk to me: 554 5.7.1 Delivery not authorized
Apr 14 16:22:47 vagrant-ubuntu-trusty-64 postfix/smtp[25261]: 6D3B160207: to=<bdero@mit.edu>, relay=DMZ-MAILSEC-SCANNER-3.mit.edu[18.9.25.14]:25, delay=331, delays=330/0/0.16/0, dsn=4.7.1, status=deferred (host DMZ-MAILSEC-SCANNER-3.mit.edu[18.9.25.14] refused to talk to me: 554 5.7.1 Delivery not authorized)
```

Inspecting the contents of the message confirms that postfix is working, and that it's good enough for debugging for me :+1: :

```
(starcellbio)vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo postcat -vq 6D3B160207
postcat: name_mask: all
postcat: inet_addr_local: configured 3 IPv4 addresses
postcat: inet_addr_local: configured 3 IPv6 addresses
*** ENVELOPE RECORDS deferred/6/6D3B160207 ***
message_size:             601             629               1               0             601
message_arrival_time: Tue Apr 14 16:17:16 2015
create_time: Tue Apr 14 16:17:16 2015
named_attribute: log_ident=6D3B160207
named_attribute: rewrite_context=local
sender: starcellbio-admin@mit.edu
named_attribute: log_client_name=localhost
named_attribute: log_client_address=127.0.0.1
named_attribute: log_client_port=52983
named_attribute: log_message_origin=localhost[127.0.0.1]
named_attribute: log_helo_name=vagrant-ubuntu-trusty-64
named_attribute: log_protocol_name=ESMTP
named_attribute: client_name=localhost
named_attribute: reverse_client_name=localhost
named_attribute: client_address=127.0.0.1
named_attribute: client_port=52983
named_attribute: helo_name=vagrant-ubuntu-trusty-64
named_attribute: protocol_name=ESMTP
named_attribute: client_address_type=2
named_attribute: dsn_orig_rcpt=rfc822;bdero@mit.edu
original_recipient: bdero@mit.edu
recipient: bdero@mit.edu
*** MESSAGE CONTENTS deferred/6/6D3B160207 ***
regular_text: Received: from vagrant-ubuntu-trusty-64 (localhost [127.0.0.1])
regular_text:   by vagrant-ubuntu-trusty-64 (Postfix) with ESMTP id 6D3B160207
regular_text:   for <bdero@mit.edu>; Tue, 14 Apr 2015 16:17:16 +0000 (UTC)
regular_text: MIME-Version: 1.0
regular_text: Content-Type: text/plain; charset="utf-8"
regular_text: Content-Transfer-Encoding: 7bit
regular_text: Subject: StarCellBio registrationConfirm E-mail Address
regular_text: From: starcellbio-admin@mit.edu
regular_text: To: bdero@mit.edu
regular_text: Date: Tue, 14 Apr 2015 16:17:16 -0000
regular_text: Message-ID: <20150414161716.24596.96021@vagrant-ubuntu-trusty-64>
regular_text: 
regular_text: You have just been registered and confirmed a StarCellBio account. This is a confirmation email.
*** HEADER EXTRACTED deferred/6/6D3B160207 ***
*** MESSAGE FILE END deferred/6/6D3B160207 ***
```

**Comment by bdero** [comment]
Merging this - we might want to make a note in the dev docs

**Comment by pdpinch** [comment]
@bdero I don't follow what you mean by 'we might want to make a note in the dev docs'

Do you want to open an issue?

**Comment by bdero** [comment]
What I meant was we might want to put some info in this document: https://github.com/starteam/starcellbio_html/blob/develop/docs/DeveloperGuide.rst

Specifically, it might be helpful to add quick tips about using postfix to help debug email-related issues on a vagrant box. I'll add a low priority issue.

**Pull request merged**
