### PR TITLE
ab: intensity page, sample column

### LINKED ISSUE #427: Western Blot: band intensity page, small edits
1) Default intensity should be medium,
2) Give more width to the sample name column,
3) Limit the sample to 2 lines and ellipsis.

### PR DESCRIPTION
**Pull request by annagav**
Fix #427

### CODE REVIEW

**Comment by noisecapella** [comment]
This PR looks fine, however I don't see anything regarding "Default intensity should be medium" from the issue linked above

**Comment by annagav** [comment]
That I already changed in a merged PR (#432).

**Comment by noisecapella** [comment]
It looks like that PR sets a default band width size, not the default intensity. If you add a number in the band size page the new slider added is set all the way to the left, with a value of 0

**Comment by annagav** [comment]
oh, yes, you are right :)

**Comment by noisecapella** [comment]
Can you rebase?

**Comment by annagav** [comment]
@noisecapella, could please look at this one more time?

**Comment by noisecapella** [comment]
:+1:

**Pull request merged**
