### PR TITLE
NSF Exercise #3 facs parser completed

### PR DESCRIPTION
**Pull request by annagav**
Added 'duration' to 'simple_parser' for sample attribute matching.

Depends on #123 and #119.

### CODE REVIEW

**Comment by pdpinch** [comment]
@annagav how should I test this?

**Comment by annagav** [comment]
This file contains the mapping between samples and graphs: StarCellBio-> curriculum->lisa'a exercises->exercise 3->coding->SCB Coding Exercise 3_v5.xlsx.

**Comment by annagav** [comment]
Fixed graphs for ConstActive strain with 'growth media only' treatment.

**Comment by pdpinch** [comment]
LGTM!

**Comment by pdpinch** [comment]
@bdero Now that we have these PRs done ( #126 #123 and #119 ), can we do a deploy? 

Wednesday is fine.

**Comment by bdero** [comment]
Alright, getting right to it!

**Comment by bdero** [comment]
Now live on https://scbdev.mit.edu .

**Pull request merged**
