### PR TITLE
ab: microscopy sample prep

### LINKED ISSUE #200: As instructor, I can choose the microscopy analysis and conditions
screen shot 2016-03-24 at 12 24 49 pm

> Within the Microscopy section of the Assignment Builder, the instructor will define the available microscopy analysis and the relationship between these analyses and the samples previously defined in the Experimental Setup pages. In this page the instructor will be able to define the (1) microcopy analyses (for ex: brightfield, dye/stain, antibody-labeling IF, antibody-labeling IHC, etc.) and (2) conditions associated with these analyses (the actual names of the dyes/stains, antibodies, etc.) available to the students for experimentation.
> 
> starcellbio_html repository docs/problemsetbuilder/User Interface Design Documents - Jamie Waters/SCB_ProblemSetBuilder_09_Microscopy.pdf the question text on page 4 in 'SCB_ProblemSetBuilder_09_Microscopy.pdf has been updated. For the updated question wording, please see the design sketch document, 'Instructor Account UI - Microscopy Ver5.pdf'
> 
> starcellbio_html repository docs/problemsetbuilder/User Interface Sketches/Microscopy/Instructor Account UI - Microscopy Ver5.pdf' → notes on the functionality required in each step to set up the microscopy experimental technique. Notes on each step are in blue text. However, design elements and layout have been modified by the graphic/user interface designer. In these cases, defer to the graphic designer document, listed above.
> 
> The graphic designer did not detail each step of setting up a microscopy experimental technique. In total there are 3 questions/steps to set up a microscopy experimental technique, and the designer sketched out steps 2 and 3. For step 1 (question wording and answer choices), please see the design sketch document, 'Instructor Account UI - Microscopy Ver5.pdf'.

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?

Fix #200 
#### What's this PR do?

Enable microscopy technique, and add the first page of microscopy setup, the `SamplePrep` page.

### CODE REVIEW

**Comment by noisecapella** [comment]
I'm getting an error after clicking 'Save and Continue' from Select Techniques:
screenshot from 2016-06-30 14-59-37

**Comment by pdpinch** [comment]
@annagav Does this go with an issue? If not, please make one.

**Comment by annagav** [comment]
I am pretty sure you created one some time ago. I just need to find it.

**Comment by annagav** [comment]
@noisecapella, I fixed the error.

**Comment by noisecapella** [comment]
:+1:

**Pull request merged**
