### PR TITLE
ab: concentration defined units

### LINKED ISSUE #389: in protocol screen, prepopulate units for variables
Alison can you comment on this issue with the requirements?

### PR DESCRIPTION
**Pull request by annagav**
Fix #389 

Adjustments to the database:
ALTER TABLE instructor_drug MODIFY concentration_unit VARCHAR(50) CHARACTER SET utf8;

### CODE REVIEW

**Comment by noisecapella** [comment]
When saving one of the unicode concentration amounts I get this error:
screenshot from 2015-11-10 14 38 43

**Comment by annagav** [comment]
Altered field concentration_unit in instructor_drug table to set the character set to utf-8.

**Comment by noisecapella** [comment]
Can you add a database migration to do this using [RunSQL](https://docs.djangoproject.com/en/1.8/ref/migration-operations/#runsql)?

**Comment by annagav** [comment]
Added a database migration and sqlparse.

**Comment by noisecapella** [comment]
What's sqlparse for?

**Comment by noisecapella** [comment]
Nevermind, just read the docs

**Comment by noisecapella** [comment]
I'm getting this error when running `./manage.py migrate`:

```
CommandError: Conflicting migrations detected (0007_concentration_units_utf8, 0007_wb_bands in instructor).
```

You may need to rebase and adjust the migrations accordingly

**Comment by annagav** [comment]
Rebased

**Comment by noisecapella** [comment]
Can you rename the migration inside this PR instead? Since the other migration is already merged we can't change it anymore

**Comment by annagav** [comment]
Done

**Comment by noisecapella** [comment]
:+1: 

I did notice this UI quirk:
- select a concentration unit
- click on textbox
- try to select another concentration unit

But it's probably out of the scope of this issue

**Pull request merged**
