### PR TITLE
replaced soyutils from google with npm soyutils

### LINKED ISSUE #583: Add instructions on how to download soyutils library and remove it from the repo
soyutils is used in the build process, but doesn't need to be part of the web app. 

We should encourage users to download and run it themselves, so we don't have to worry about licensing.

### PR DESCRIPTION
**Pull request by pdpinch**
#### What are the relevant tickets?

fixes #583 
#### What's this PR do?

Removes soyutils.js from Google which, according to TLO, has an incompatible license. 
#### Where should the reviewer start?

@starteam/devops Can you review the changes to the ansible provisioning and travis yml?

@annagav since there are no test for the assignment builder javascript, can you please check to see if the assignment builder is still functional?
#### How should this be manually tested?

Check out a clean repository without any build artifacts. Do a `vagrant up` and run the app. See if the student view and the assignment builder work as expected. 
#### Any background context you want to provide?

There are a few other libraries that need to be removed / replaced as well. See #584. 
#### What GIF best describes this PR or how it makes you feel?

Not a gif, but you get the idea:

img

### CODE REVIEW

**Comment by blarghmatey** [comment]
From the Ansible side it looks fine to me.

**Comment by annagav** [comment]
I get a gray page with this error:
screen shot 2016-07-06 at 4 00 14 pm

**Comment by annagav** [comment]
This PR contains my commit from PR #640

**Comment by pdpinch** [comment]
@annagav did you run it on a new vagrant box, or an existing one?

On an existing one, I think you need to run `vagrant provision` and then run the build script again.

**Comment by annagav** [comment]
I ran it on a new vagrant box.

**Comment by annagav** [comment]
I defined an assignment and published it. On click of 'Preview' in the Dashboard I got this:

screen shot 2016-07-07 at 3 48 05 pm

**Comment by jmclaus** [comment]
@pdpinch @annagav @laleman 

`soytutils.js` is mandatory, it contains the libraries necessary to run a compiled soy template. 

`soyutils_noog.js` ie:

https://raw.githubusercontent.com/mattpowell/soyutils/master/soyutils_nogoog.js

won't work here, it is a commonjs module that needs to be 'browserified' before it can be used by the browser.

But after some time, I did find a place where `soytutils.js` is available as a node module, in a package called `gulp-soy`:

https://www.npmjs.com/package/gulp-soy

So if we add the entry `"gulp-soy": "^1.0.1"` in our `package.json`, we end up having `soytutils.js` buried a bit, at the following location:

node_modules/gulp-soy/node_modules/closure-templates/soyutils.js'

If we put the above in `static_assets.yml`, `soytutils.js` will end up in the minified JS bundle and the application will run, I just tested it.

It's a bit of a hack but lets us circumvent the licensing issue as `soyutils.js` will not be distributed with the application. We do not know what version of the soy template 'runtime' is bundled though.

If you look at the `gulp-soy` plugin source code:

https://github.com/jbdemonte/gulp-soy/blob/master/index.js#L78

you can see how their `soyutils.js` is build from the following node package:

https://www.npmjs.com/package/closure-templates

1. We could build our own `soyutils.js` by using the above technique. Since closure-templates has 9 releases, we probably will find a matching file with the one currently used.

2. We could just use gulp with various plugins including `gulp-soy` to build our minified JS and CSS thus replacing most the code in builp.py

That file has 3 reported issues:

https://github.com/starteam/starcellbio_html/issues/43
https://github.com/starteam/starcellbio_html/issues/46
https://github.com/starteam/starcellbio_html/issues/47

that would most likely be solved along the way.

Please let me know what you think.

**Comment by jmclaus** [comment]
@pdpinch @annagav Should I push a commit on this branch with the above so you can test it out?

**Comment by jmclaus** [comment]
@pdpinch @annagav PR is [here](https://github.com/starteam/starcellbio_html/pull/769).

**Comment by jmclaus** [comment]
@pdpinch @annagav  We should close this without merging, related [PR](https://github.com/starteam/starcellbio_html/pull/769) has been merged.

**Comment by pdpinch** [comment]
Thanks @jmclaus

**Pull request closed without merging**
