### PR TITLE
NSF#3 western blot model completed

### PR DESCRIPTION
**Pull request by annagav**
Modifications for 'parser_fixed'-> 'transfer_function' equals 'delta':
- Added new 'rule' option for Western Blot marks parser, to accept a drug value '\* ANY\* ' .
- Added 'duration' to the rule parser.  

Modifications to NSF Exercise#3:
- Populated the western blot model.

### CODE REVIEW

**Comment by pdpinch** [comment]
Anna, can you edit the description for the PR to give some more detail? If it is just data entry, let us know -- but it looks like you may have changed a couple of other things?

**Comment by pdpinch** [comment]
@annagav I know this is kind of a pain, but given the fact that we're trying improve the quality of this code and repository, could you split this into two (or three?) pull requests?

One should just be the data changes for NSF #3. The other one (or two) would be about the changes to the parser function. 

That way we can make more clear the separation between function and content. And if anyone needs to look back at this repo to understand what was going on, it will be more clear. 

Thanks!

**Comment by pdpinch** [comment]
Oh, otherwise this looks fine to me. I'd merge it if it were two PRs.

**Comment by annagav** [comment]
Refactoring is done. This PR contains only coding modifications to master_model.js. The rest of the modifications are here #134.

**Comment by pdpinch** [comment]
Thanks!

**Comment by pdpinch** [comment]
:+1:

**Pull request merged**
