### PR TITLE
ab: publish assignment

### LINKED ISSUE #501: Publish assignment so student can view
- [x] compile assignment, similar to preview
- [x] save resulting json to student table

### PR DESCRIPTION
**Pull request by annagav**
Fix #501

### CODE REVIEW

**Comment by pdpinch** [comment]
I'm having problems with publishing some experiments, which I think may be bugs in the compiler. 

The first problem I had was with an experiment with only one strain. When I got to the add strains portion of the setup, I didn't get a pop-up window at all. No console messages. 

In trying to reproduce that error, I'm now getting a blank screen after I sign into my course as a student. Looking at the console I see a message:

```

              <span style="color: #000000; font-size: small;">This
              feature is currently unavailable in
              StarCellBio.</span>

              <span style="color: #000000; font-size: small;"><span style="line-height: 21px;"><br></span></span>

              <span style="font-size: small;"><br></span>
```

But it doesn't get to the user. 

I'm not sure if it's related, but I can't get the json stored in the backend.assignments table to validate. One thing that looks especially suspicious is that the values for drug_id aren't quoted.

**Comment by annagav** [comment]
Have you defined the treatments and the western blot technique?

**Comment by pdpinch** [comment]
I have defined the treatments and the western blot technique. 

It actually seems to happen when I have more than one assignment in the same course. One assignment is OK, but two assignments blows up. 

Otherwise, this appears to be working OK.

**Comment by annagav** [comment]
Rebased and fixed!

**Comment by annagav** [comment]
@pdpinch, Could you please take a look at it again, so that I can rebase PR #532?

**Comment by pdpinch** [comment]
OK. Doing it now.

**Comment by pdpinch** [comment]
Ok, this is working for me now. I published two assignments, each with only one strain. I was able to do western blots for both of them.

:+1:

**Pull request merged**
