### PR TITLE
ab facs: name for x axis

### LINKED ISSUE #628: FACS: x axis label
We can set the x-axis label to be the same as the Condition name.

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?

Fix #628 
#### What's this PR do?

Label x axis with condition name.

### CODE REVIEW

**Comment by pdpinch** [comment]
@annagav any thoughts on why tests are failing here? 

If it's not obvious, I'll start doing a review and let you know what I find.

**Comment by annagav** [comment]
I am working on this test ...

**Comment by annagav** [comment]
I ran the Selenium tests locally and they passed ok.

**Comment by annagav** [comment]
Rebuilding now here...

**Comment by pdpinch** [comment]
👍

**Pull request merged**
