### PR TITLE
ab: current section name in green bar

### LINKED ISSUE #392: Display current section name in green bar over form
Currently this always displays `Assignment Setup` 

It should be updated to reflect the current section, e.g `Experiment Setup`

Once this change is made, we can omit the section title and intro from the forms.

### PR DESCRIPTION
**Pull request by annagav**
Display current section name in the green bar on the right side. Fix #392

### CODE REVIEW

**Comment by noisecapella** [comment]
It looks like the title is missing for edit_text and edit_treatments

**Comment by noisecapella** [comment]
I think #392 also requires the removal of 'Experiment Setup' and 'Assignment Setup' from the body of the forms since it's in the header instead.

**Comment by annagav** [comment]
I just rebased this branch to reflect the latest changes. 'edit_text' is waiting to be removed and 'edit_treatments' has been removed in the last PR.

**Comment by annagav** [comment]
I think Peter changed the description of issue after I made the changes :)
We haven't decided yet what write below the green bar, so it won't be consistent across all pages, but I have removed the repetitions in the section name.

**Comment by noisecapella** [comment]
Sounds good, I'll take another look

**Comment by noisecapella** [comment]
It looks like the header is still missing from the `assignments_edit_text` view, otherwise this looks good

**Comment by noisecapella** [comment]
Oh nevermind, it will be removed you said

**Comment by noisecapella** [comment]
:+1:

**Pull request merged**
