### PR TITLE
ab: Western Blot page 1

### PR DESCRIPTION
**Pull request by annagav**
Select lysate type: only whole cell available for now.
Select percentage of acrylamide.

### CODE REVIEW

**Comment by pdpinch** [comment]
This looks good to me, but I'm noticing that I don't see "Select Techniques" in this branch. Should I be seeing that?

**Comment by annagav** [comment]
I rebased it, should be there now.

**Comment by annagav** [comment]
@pdpinch, is it good for merging?

**Comment by pdpinch** [comment]
:+1:

**Pull request merged**
