### PR TITLE
ab: show message before publishing

### LINKED ISSUE #481: Dashboard: when publishing an assignment, show a confirmation message
As an instructor, I need to know that when I publish an assignment, I will no longer be able to edit it.

### PR DESCRIPTION
**Pull request by annagav**
Fix #481

### CODE REVIEW

**Comment by pdpinch** [comment]
:+1: on the message, but I can still edit after I publish & the state changes to public. Is that what I should expect?

Also, is there any way to return to private?

**Comment by annagav** [comment]
There is no way to return to private.

**Comment by annagav** [comment]
The actual 'view' functionality is in different PR.

**Comment by pdpinch** [comment]
I see that now. This is good to go now.

**Pull request merged**
