### PR TITLE
AB Micro: Save scroll position of the page Analyze

### LINKED ISSUE #733: Assignment builder microscopy: Remember instructor's position on page
Remember the instructor's position on the microscopy analyze page. This will help when instructors are uploading lots of images for many samples.

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?
Fix #733

### CODE REVIEW

**Comment by pdpinch** [comment]
I found that sometimes the scroll values wasn't an integer, so you should convert it to an integer.

**Comment by pdpinch** [comment]
Looks like I've been sitting on this PR for almost a year now. 

Is it still relevant?

**Comment by jmclaus** [comment]
@pdpinch Not really sure. @laleman do you still think this feature should be implemented? If so, I can look into this PR, see how it fares with current code and merge it.

**Comment by laleman** [comment]
I can look into this when I test the microscopy stuff in the development site. Not sure if it is relevant anymore with the new drag and drop system in microscopy.

**Pull request closed without merging**
