### PR TITLE
wb: correct bands size and intensity ex2

### LINKED ISSUE #161: NSF Exercise 2 - Errors in western blotting bands
The bands are not appearing correctly on the western blot:
PGK1 should produce bands in every lane at 44 kDa.

Protein X antibody should detect bands at 82 kDa (low intensity) in 'No tags growth media', 'ProY null growth media', 'His-Prox-FLAG growth media', 'His-ProY-FLAG growth media'. Also at 84 kDa with high intensity in 'His-Prox-FLAG growth media'.

Protein Y antibody should detect at 230 kDa low intensity in 'No tags growth media', 'ProX-null growth media', 'His-ProX-FLAG growth media', 'his-proY-FLAG growth media'. Also at 232 kDa high intensity in 'his-proY-FLAG growth media'.

6xHis antibody should detect at 84 kDa (high intensity) in 'his-prox-flag growth media', 40 kDa (med intensity) in 'his-prox-flag growth media+prok', and 232 kDA high intensity in 'his-proy-flag growth media'.

anti-flag antibody should detect at 84 kDa (high intensity) 'his-prox-FLAG growth media' and 232 kDa high intensity in 'his-proy-flag growth media'.

The intensity mentioned above (high, medium, low) refers to the intensity of the band at the default exposure time, which is 1 minute.

### PR DESCRIPTION
**Pull request by annagav**
Fix #161

### CODE REVIEW

**Comment by pdpinch** [comment]
I'm only seeing one of these bands:

> The protein X antibody should detect two bands, one at 82 (low intensity) and one at 84 (high intensity), in the 'His-ProX-Flag, Growth Media + buffer' sample, but I only see the band at 84 kDa.

screen shot 2015-08-08 at 8 42 06 am

I think I must be doing something wrong. I'm going to move on to the other PRs and come back to this later.

**Comment by annagav** [comment]
There are 2 bands displayed. Because the exposure time is so high the bands became very thick and merged together.

**Comment by annagav** [comment]
Is this good for merging? Alison was asking to review this since this is a high priority issue for the NSF deadline.

**Comment by pdpinch** [comment]
Sorry for the delay, this is ready for :tram:

**Pull request merged**
