### PR TITLE
assignment text: table headers format

### LINKED ISSUE #213: NSF Exercise #1 - Add a table in the assignment text -> background information -> microscopy
There should be a table in the microscopy section within background information of the assignment text. The table has two rows and two columns. The heading row has 'Conditions' and 'Description'. The heading row should be in bold - see issue #160

### PR DESCRIPTION
**Pull request by annagav**
Fix #213, #160.

### CODE REVIEW

**Comment by giocalitri** [comment]
This cannot be merged: please rebase first

**Comment by annagav** [comment]
Done!

**Comment by giocalitri** [comment]
the functionality is fine, although I think you should replace the `<b>` with `<strong>`: the result on the page will be the same, but the semantic will be different.

**Comment by annagav** [comment]
Done!

**Comment by giocalitri** [comment]
Sorry for not mentioning this before: can you please fix the line length of the code you changed?

**Comment by giocalitri** [comment]
Please be consistent with the style:
 code like

```
<thead><td><strong>Cell line</strong></td>
<td><strong>Average doubling time in serum free media ± standard deviation (hours) <strong></td>
</thead>
```

should be like

```
<thead>
    <td>
        <strong>Cell line</strong>
    </td>
    <td>
        <strong>Average doubling time in serum free media ± standard deviation (hours) <strong>
    </td>
</thead>
```

**Comment by annagav** [comment]
I agree, but neither of the files are formatted in any way.

**Comment by giocalitri** [comment]
I totally agree with you and I am asking to format only the code you touched.

**Comment by annagav** [comment]
Done!

**Comment by giocalitri** [comment]
looks good: merging

**Pull request merged**
