### PR TITLE
Added the ODL PR Template

### PR DESCRIPTION
**Pull request by justinabrahms**

### CODE REVIEW

**Comment by jamiefolsom** [comment]
Is this based on this new gh feature? https://github.com/blog/2111-issue-and-pull-request-templates? Does the filename have to be uppercase? I opened a PR today on TeachersPortal, and didn't get the template pre-pasted. Possibly doesn't work with the hub gem, which is how I did it?

**Comment by jamiefolsom** [comment]
Yep, according to this issue, hub doesn't use the template yet. https://github.com/github/hub/issues/1118

**Comment by justinabrahms** [comment]
Yes. It's based on that feature.

**Comment by jamiefolsom** [comment]
Looks GTM. :metal:

**Comment by giocalitri** [comment]
@jamiefolsom are you sure we count that symbol as well? :-)

**Comment by justinabrahms** [comment]
Yes. He submitted a PR to make that part of the default set. :)

On Mon, Feb 22, 2016 at 3:46 PM, Giovanni Di Milia <notifications@github.com

**Comment by jamiefolsom** [comment]
https://github.com/justinabrahms/review-counter/blob/master/main.py#L46 :100:%

**Comment by giocalitri** [comment]
hey: now you are cheating: this PR will count 2

**Comment by justinabrahms** [comment]
You can always edit his comment. :-P

On Monday, February 22, 2016, Giovanni Di Milia notifications@github.com
wrote:

> hey: now you are cheating: this PR will count 2
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/starteam/starcellbio_html/pull/592#issuecomment-187377938
> .

## 

Sent via mobile phone.

**Comment by jamiefolsom** [comment]
Edited. Need a `return` here? https://github.com/justinabrahms/review-counter/blob/master/main.py#L40

**Comment by justinabrahms** [comment]
No. If two people review the code, they should both get credit.

**Comment by jamiefolsom** [comment]
Agreed; in this case, @giocalitri, for example!

**Pull request merged**
