### PR TITLE
Feature/sutd ex2 analysis

### LINKED ISSUE #547: SUTD Exercise 2 bug: errors on flow cytometry setup page
The following changes should be made:
1. 'Fixed' should stay in the Cell Treatment column once a sample is selected
2. PI should appear in the 'conditions' column
3. The Analysis column should say Dye/Stain (this will match the option in the assignment builder)

### PR DESCRIPTION
**Pull request by annagav**
Fix #547

### CODE REVIEW

**Comment by noisecapella** [comment]
Can you squash the `temp` commit with the other one?

**Comment by annagav** [comment]
oops, forgot to do that!

**Comment by annagav** [comment]
Done

**Comment by noisecapella** [comment]
:+1:

**Pull request merged**
