### PR TITLE
#48 Added get_user.js unit test

### PR DESCRIPTION
**Pull request by blarghmatey**
- Added unit test for get_user.js
- Added pre-commit hooks
- Moved development dependencies to requirements.dev.txt
- Fixed some linting errors
- Added travis config for building with Travis CI

### CODE REVIEW

**Comment by justinabrahms** [comment]
As mentioned in hipchat, can we remove or skip the tests that don't pass? I'd like to make a line in the sand for "Starting now, all PRs must have passing tests" even if it's just a few tests.

**Comment by justinabrahms** [comment]
cc @annagav. You should be comfortable with the implications of this pre-commit hook (if you choose to install it). I'd like your thoughts, if you would.

**Comment by blarghmatey** [comment]
I'm happy to answer any questions or modify linting settings as needed. I just set up an initial configuration for linting with eslint and flake8 but I'm happy to help modify that to whatever will best suit the needs of everyone working on the project.

**Comment by justinabrahms** [comment]
:+1:

**Pull request merged**
