### PR TITLE
micro: remove black image in nucleus_final

### LINKED ISSUE #219: NSF Exercise #1 - Microscopy images aren't appearing for 3 samples
Microscopy images aren't appearing for 3 samples:

GFP-Mut ProB
GFP-Nuc
GFP-PM

### PR DESCRIPTION
**Pull request by annagav**
Fix #219

### CODE REVIEW

**Comment by carsongee** [comment]
I'm not sure how to verify this is fixed, and it looks like there is still some communication in the issue.  Maybe you could run me through it real quick?  The code/change looks fine in general, but not sure about functionality.

**Comment by annagav** [comment]
The conversation is about how Alison and Lourdes tried to test this but I haven't yet made the change. 
The way you test is you perform the experiment and if your don't see a black image for 
GFP-Mut ProB
GFP-Nuc
GFP-PM 
then it is either fixed, or the random algorithm did not choose this 'bad' image this time.

**Comment by pdpinch** [comment]
Oh, I didn't realize there's randomization in the microscopy images!

Can you point out the relevant code for the randomization? Maybe there's a way to test it more methodically.

**Comment by annagav** [comment]
https://github.com/starteam/starcellbio_html/blob/develop/html_app/components/MicroscopyModelFactory.js#L68

**Comment by pdpinch** [comment]
:ok: I'm convinced

**Pull request merged**
