### PR TITLE
ab: select not yet created course

### LINKED ISSUE #395: Course setup: when entering name for a new course, enable the select radio button
When entering a new name for a course, enable the select radio button when the instructor starts to type in the text boxes. This will be more intuitive than having to click 'Save' before the radio button is enabled.

### PR DESCRIPTION
**Pull request by annagav**
Fix #395

### CODE REVIEW

**Comment by noisecapella** [comment]
What's fixed by this PR? I'm not sure what to look for

**Comment by annagav** [comment]
The radio button is enabled for the extra course form, so that course can be created and selected in the same form submission.

**Comment by noisecapella** [comment]
Ok, thanks. I can create a new course fine but I get an error when I both select and create the new course:

```
Internal Server Error: /ab/assignments/course_modify/
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/starcellbio/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/.virtualenvs/starcellbio/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/vagrant/instructor/common.py", line 274, in course_modify
    if not long(pk) == assignment.course.id:
ValueError: invalid literal for long() with base 10: 'None'
[12/Jan/2016 14:38:36] "POST /ab/assignments/course_modify/ HTTP/1.1" 500 95070
```

**Comment by annagav** [comment]
Fixed!

**Comment by noisecapella** [comment]
Everything works now :+1:

**Pull request merged**
