### PR TITLE
Micro: fix load images notification

### LINKED ISSUE #737: SUTD Exercises: Text after microscopy load images is longer than window.
Text that appears within the message window after "loading" microscopy samples in the microscopy appears to be too long and not consistent with the text in the NSF exercises. They all need to be the same. Change text within this window to the text in the NSF exercises. 
screen shot 2016-10-24 at 3 31 15 pm

### PR DESCRIPTION
**Pull request by annagav**
#### What are the relevant tickets?

Fix #737
#### What's this PR do?

Remove the word `microscope` in order to fit the message.

screen shot 2016-10-28 at 12 53 48 pm

### CODE REVIEW

**Comment by pdpinch** [comment]
I'm not sure how to test this. Which assignments can I test this with?

**Comment by annagav** [comment]
It happens only in SUTD assignments, not in NSF.

**Comment by noisecapella** [comment]
Edit: nevermind, forgot to rebuild

**Review by noisecapella — APPROVED** [review]
:+1:

**Pull request merged**
