### PR TITLE
Improve a11y

### PR DESCRIPTION
**Pull request by jmclaus**
This is a first pass at improving accessibility on the instructor side. Focus outlines were reinstated on most elements. Odd constructs like anchors containing buttons were removed in favor of simple buttons. Tabbing order was corrected for the navigation buttons. Trash icons can now be accessed via keyboard as well as labels associated to file input types.

### CODE REVIEW

**Comment by jmclaus** [comment]
@pdpinch I have no further changes to merge except the above. Once done, please feel free to do a release.

**Comment by annagav** [comment]
@jmclaus how should this be tested?

**Comment by jmclaus** [comment]
@annagav Just tab to various GUI elements on the instructor side, they'll show they have focus and react to keyboard events ie for buttons, ENTER/SPACE, dropdowns, UP/DOWN etc. FYI, this is work in progress and some elements may not be reached by TAB or SHIFT+TAB as for example the popup windows etc.

**Review by annagav — APPROVED** [review]
👍

**Comment by jmclaus** [comment]
@pdpinch PR is merged and StarCellBio is ready for new release. @annagav thanks for your quick review.

**Pull request merged**
